### ISSUE TITLE
How to add LTI to Canvas

### ISSUE THREAD

**Issue by adamtyoung** [harvard-edtech/caccl#1]
This is just a question that seems to be missing from the docs, but after getting an app built, what is the launch endpoint and secret / secret combo that one would use for adding it as an app in Canvas? Thanks!

**Comment by gabeabrams** [comment]
This is a great question! I'll respond here and then take some time to add this info to the docs.

There are two key/secret pairs that Canvas needs. We call them **installationCredentials** and **developerCredentials**. 

**installationCredentials** – You just make these up. The consumer_key and consumer_secret can be anything. When you install your LTI app into Canvas, you'll be asked for the consumer_key and consumer_secret. To add those values to your app, edit `config/installationCredentials.js`

**developerCredentials** – You need these credentials if your app accesses the Canvas API. If you don't need to access the Canvas API, set `disableClientSideAPI: true` and `disableServerSideAPI: true` when initializing CACCL. To get these developerCredentials (client_id and client_secret), you need to generate a new developer key following these directions:
https://community.canvaslms.com/docs/DOC-12657-4214441833
Once you've created the new developer key, you'll find the client_id in plain text under the "details" column. The client_secret will be shown if you click the "Show Key" button right under the client_id.
Then, add the client_id and client_secret to `config/developerCredentials.js`

Does this answer your question?

**Comment by adamtyoung** [comment]
Now that I am looking, those original instructions couldn't have been clearer in the docs! Thanks for your patience. Do I place the disableClientSideAPI: true and disableServerSideAPI: true directives in one of the files in the config dir? Again, thanks so much for your help.

**Comment by adamtyoung** [comment]
Also, another completely noob question. Once I have run `npm run build`, can I then just deploy the contents of the build dir to my production server? That is, without the other files for the dev server etc?

**Comment by gabeabrams** [comment]
Thank you for these insightful followup questions. You're highlighting giant holes in my documentation.  I've updated the documentation (see https://github.com/harvard-edtech/caccl#adding-your-app-to-canvas specifically) for a hopefully better written answer to your questions. I hopefully answer your first follow-up question there. 

I added more info to the https://github.com/harvard-edtech/caccl#production-mode docs as well to answer your second question. Specifically, see the "FAQ: What do I upload to my production server?" section. TLDR: it's easiest to upload the entire project, but you can save space by deleting everything in the `/client` folder _except_ for `/client/build`.

Thank you for your valuable questions! Keep em coming you have them.

**Comment by adamtyoung** [comment]
Thanks so much for your help and for this great tool!
