### ISSUE TITLE
Using CACCL on Windows

### ISSUE THREAD

**Issue by renaatdemuynck** [harvard-edtech/caccl#16]
After some tweaking in `package.json` I found this is all that's needed to make it work on Windows:

    "scripts": {
        "test": "echo 'Error: no test specified' && exit 1",
        "start": "node index.js",
        "postinstall": "cd client && npm install",
        "build": "cd client && npm install && npm run build",
        "dev:canvas": "node ./node_modules/caccl/canvas/startPartialSimulation",
        "dev:server": "cross-env DEV=true npm start",
        "dev:client": "cd client && cross-env DEV=true npm start"
    }

* Use `cross-env` for setting environment variables
* use `&&` for chaining commands

**Comment by gabeabrams** [comment]
With the next beta, we're adding this change! Thank you for the suggestion.
