### ISSUE TITLE
What versions of LTI does this work with?

### ISSUE THREAD

**Issue by rickgm** [harvard-edtech/caccl#29]
Please update the README to indicate what version of LTI this works with, e.g., 1.1 or 1.3.

**Comment by gabeabrams** [comment]
Done. Thank you :)

**Comment by gabeabrams** [comment]
(v1.1, currently working on v1.3 but it's not available yet)

**Comment by rickgm** [comment]
lol, you handled this so quickly i thought i must not have submitted it.  Thanks for your help!

**Comment by gabeabrams** [comment]
My pleasure! Just curious, does v1.1 work for you? I'm trying to keep track of how popular a v1.3 version would be, but it's hard to gauge how many people would use it

**Comment by rickgm** [comment]
I'm just reviewing your library right now.  I notice that you don't have a license file.  Can you please create a license file?

**Comment by gabeabrams** [comment]
Ah the license is on npmjs. Sorry for the confusion. I'll add it here too. 
https://www.npmjs.com/package/caccl

It's MIT
