### ISSUE TITLE
Error on installing with init

### ISSUE THREAD

**Issue by adamtyoung** [harvard-edtech/caccl#5]
On a Mac, node version 11.9.0. When walking through the ```npm init``` steps for React + Express, fails out when trying to create the React app:
`error eslint@6.4.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.9.0"`

**Comment by gabeabrams** [comment]
HI Adam, I'm sorry for taking so long to respond!

Did you close this issue because you figured this out? My best guess is that this has something to do with the `create-react-app` package. If you haven't figured this out, I'd love to help figure out what's going on.

**Comment by adamtyoung** [comment]
Hi Gabe,
  I think it turned out to be a node update that I needed to run---thanks for your attention. Cheers,

Adam
