### ISSUE TITLE
Which operating system & node version has this been tested with?

### ISSUE THREAD

**Issue by dvitrium** [harvard-edtech/caccl#7]
We are having some issues getting this project working, we have tried running it on the latest stable version of Fedora & Debian. Could someone please recommend a tested nodejs & npm version, as well as a distribution setup to test this project?
Thank you!

**Comment by dvitrium** [comment]
Got it working by using node.js v12

**Comment by gabeabrams** [comment]
Great! Thank you for the update. I'll add a notice to the docs to use v12+
