### ISSUE TITLE
Chrome local dev http vs https sameSite cookie issue

### ISSUE THREAD

**Issue by karendolan** [harvard-edtech/caccl#9]
If you are running the local dev for a react app and in the Chrome browser continually get a message like "Session Expired Go to Canvas and reopen this page.".  But it works in the Safari & FireFox browser, it might be the Chrome schemeful-same-site parameter that forbids sameSite cookies across protocols such as https and http.

A temporary workaround for Chrome is to go into the chrome settings (chrome://flags/) and change the 
#schemeful-same-site Chrome from “default” or "enabled" to “disabled. Then, reload the Chrome browser. Set this back to default or enabled when done testing.

A longer term option may be to set up a local HTTPS cert to be used for your dev testing.

**Comment by buckett** [comment]
I've had lots of success with https://github.com/FiloSottile/mkcert for generating certificate is other projects.

**Comment by gabeabrams** [comment]
This issue should be fixed with the new version of CACCL (v2)

**Comment by gabeabrams** [comment]
Also, it might be an iframe issue. If so, see my comment in this issue:
https://github.com/harvard-edtech/caccl/issues/23
